package com.mleoni.demo_park_api.web.controller;

import com.mleoni.demo_park_api.entities.ClientSpot;
import com.mleoni.demo_park_api.jwt.JwtUserDetails;
import com.mleoni.demo_park_api.repositories.projection.ClientSpotProjection;
import com.mleoni.demo_park_api.services.ClientSpotService;
import com.mleoni.demo_park_api.services.ParkingService;
import com.mleoni.demo_park_api.web.controller.dto.ClientResponseDTO;
import com.mleoni.demo_park_api.web.controller.dto.PageableDTO;
import com.mleoni.demo_park_api.web.controller.dto.ParkingCreateDTO;
import com.mleoni.demo_park_api.web.controller.dto.ParkingResponseDTO;
import com.mleoni.demo_park_api.web.controller.dto.mapper.ClientSpotMapper;
import com.mleoni.demo_park_api.web.controller.dto.mapper.PageableMapper;
import com.mleoni.demo_park_api.web.controller.exception.ErrorMessage;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.headers.Header;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.data.web.PageableDefault;
import org.springframework.http.HttpHeaders;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;

import java.net.URI;

import static io.swagger.v3.oas.annotations.enums.ParameterIn.PATH;
import static io.swagger.v3.oas.annotations.enums.ParameterIn.QUERY;

@RequiredArgsConstructor
@RestController
@RequestMapping("api/v1/parkings")
public class ParkingController {
    private final ParkingService parkingService;
    private final ClientSpotService clientSpotService;


    @Operation(summary = "Check-in operation.", description = "Resource for entering a vehicle into the parking lot." +
            "The request requires a bearer token. Access restricted to Role='ADMIN'",
            security = @SecurityRequirement(name = "security"),
            responses = {
                    @ApiResponse(responseCode = "201", description = "Resource created successfully.",
                            headers = @Header(name = HttpHeaders.LOCATION, description = "URL to access the created resource"),
                            content = @Content(mediaType = "application/json", schema = @Schema(implementation = ClientResponseDTO.class))),
                    @ApiResponse(responseCode = "403", description = "Feature not allowed for ADMIN profile.",
                            content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorMessage.class))),
                    @ApiResponse(responseCode = "404", description = "Possible causes: <br/>" +
                            "- Customer's CPF not registered in the system; <br/>" +
                            "- No spots were found;",
                            content = @Content(mediaType = " application/json;charset=UTF-8",
                                    schema = @Schema(implementation = ErrorMessage.class))),
                    @ApiResponse(responseCode = "422", description = "Resource not processed due to invalid input data",
                            content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorMessage.class)))
            })
    @PostMapping("/check-in")
    @PreAuthorize("hasRole('ADMIN')")
    public ResponseEntity<ParkingResponseDTO> checkIn(@RequestBody @Valid ParkingCreateDTO dto) {
        ClientSpot clientSpot = ClientSpotMapper.toClientSpot(dto);
        parkingService.checkIn(clientSpot);
        ParkingResponseDTO responseDTO = ClientSpotMapper.toDto(clientSpot);
        URI location = ServletUriComponentsBuilder
                .fromCurrentRequestUri().path("/{receipt}")
                .buildAndExpand(clientSpot.getReceipt())
                .toUri();
        return ResponseEntity.created(location).body(responseDTO);
    }

    @Operation(summary = "Locate a parked vehicle", description = "Feature to return a parked vehicle " +
            "by receipt number. Request requires use of a bearer token.",
            security = @SecurityRequirement(name = "security"),
            parameters = {
                    @Parameter(in = PATH, name = "receipt", description = "Receipt number generated by check-in")
            },
            responses = {
                    @ApiResponse(responseCode = "200", description = "Resource successfully located",
                            content = @Content(mediaType = " application/json;charset=UTF-8",
                                    schema = @Schema(implementation = ParkingResponseDTO.class))),
                    @ApiResponse(responseCode = "404", description = "Receipt number not found.",
                            content = @Content(mediaType = " application/json;charset=UTF-8",
                                    schema = @Schema(implementation = ErrorMessage.class)))
            })
    @GetMapping("/check-in/{receipt}")
    @PreAuthorize("hasAnyRole('ADMIN', 'CLIENT')")
    public ResponseEntity<ParkingResponseDTO> getByReceipt(@PathVariable String receipt) {
        ClientSpot clientSpot = clientSpotService.findByReceipt(receipt);
        ParkingResponseDTO dto = ClientSpotMapper.toDto(clientSpot);
        return ResponseEntity.ok(dto);
    }

    @Operation(summary = "Checkout operation", description = "Resource for leaving a vehicle from the parking lot. " +
            "Request requires use of a bearer token. Access restricted to Role='ADMIN'",
            security = @SecurityRequirement(name = "security"),
            parameters = {@Parameter(in = PATH, name = "receipt", description = "Receipt number generated by check-in",
                    required = true)
            },
            responses = {
                    @ApiResponse(responseCode = "200", description = "Resource updated successfully",
                            content = @Content(mediaType = " application/json;charset=UTF-8",
                                    schema = @Schema(implementation = ParkingResponseDTO.class))),
                    @ApiResponse(responseCode = "404", description = "Non-existent receipt number or" +
                            "the vehicle has already been checked out.",
                            content = @Content(mediaType = " application/json;charset=UTF-8",
                                    schema = @Schema(implementation = ErrorMessage.class))),
                    @ApiResponse(responseCode = "403", description = "Resource not allowed for CLIENT profile",
                            content = @Content(mediaType = " application/json;charset=UTF-8",
                                    schema = @Schema(implementation = ErrorMessage.class)))
            })
    @PutMapping("/check-out/{receipt}")
    @PreAuthorize("hasAnyRole('ADMIN')")
    public ResponseEntity<ParkingResponseDTO> checkout(@PathVariable String receipt) {
        ClientSpot clientSpot = parkingService.checkOut(receipt);
        ParkingResponseDTO dto = ClientSpotMapper.toDto(clientSpot);
        return ResponseEntity.ok(dto);
    }

    @Operation(summary = "Find customer parking records by CPF", description = "Find the " +
            "customer parking records by CPF. Request requires the use of a bearer token.",
            security = @SecurityRequirement(name = "security"),
            parameters = {
                    @Parameter(in = PATH, name = "cpf", description = "CPF number for the client to be consulted",
                            required = true
                    ),
                    @Parameter(in = QUERY, name = "page", description = "Represents the returned page",
                            content = @Content(schema = @Schema(type = "integer", defaultValue = "0"))
                    ),
                    @Parameter(in = QUERY, name = "size", description = "Represents the total number of elements per page",
                            content = @Content(schema = @Schema(type = "integer", defaultValue = "5"))
                    ),
                    @Parameter(in = QUERY, name = "sort", description = "Default sort field 'entry_date,asc'. ",
                            array = @ArraySchema(schema = @Schema(type = "string", defaultValue = "entry_date,asc")),
                            hidden = true
                    )
            },
            responses = {
                    @ApiResponse(responseCode = "200", description = "Resource successfully located",
                            content = @Content(mediaType = " application/json;charset=UTF-8",
                                    schema = @Schema(implementation = PageableDTO.class))),
                    @ApiResponse(responseCode = "403", description = "Resource not allowed for CLIENT profile",
                            content = @Content(mediaType = " application/json;charset=UTF-8",
                                    schema = @Schema(implementation = ErrorMessage.class)))
            })
    @GetMapping("/cpf/{cpf}")
    @PreAuthorize("hasRole('ADMIN')")
    public ResponseEntity<PageableDTO> getAllParkingByCpf(@PathVariable String cpf,
                                                          @PageableDefault(size = 5, sort = "entryDate",
                                                                  direction = Sort.Direction.ASC) Pageable pageable) {
        Page<ClientSpotProjection> projection = clientSpotService.findAllByClientCpf(cpf, pageable);
        PageableDTO dto = PageableMapper.toDto(projection);
        return ResponseEntity.ok(dto);
    }

    @Operation(summary = "Find the logged in customer's parking records.",
            description = "Find the logged in customer's parking records. " +
                    "Request requires use of a bearer token.",
            security = @SecurityRequirement(name = "security"),
            parameters = {
                    @Parameter(in = QUERY, name = "page",
                            content = @Content(schema = @Schema(type = "integer", defaultValue = "0")),
                            description = "Represents the returned page"
                    ),
                    @Parameter(in = QUERY, name = "size",
                            content = @Content(schema = @Schema(type = "integer", defaultValue = "5")),
                            description = "Represents the total number of elements per page"
                    ),
                    @Parameter(in = QUERY, name = "sort", hidden = true,
                            array = @ArraySchema(schema = @Schema(type = "string", defaultValue = "dataEntrada,asc")),
                            description = "Default sort field 'dataEntrada,asc'. ")
            },
            responses = {
                    @ApiResponse(responseCode = "200", description = "Resource successfully located",
                            content = @Content(mediaType = " application/json;charset=UTF-8",
                                    schema = @Schema(implementation = ParkingResponseDTO.class))),
                    @ApiResponse(responseCode = "403", description = "Feature not allowed for ADMIN profile",
                            content = @Content(mediaType = " application/json;charset=UTF-8",
                                    schema = @Schema(implementation = ErrorMessage.class)))
            })
    @GetMapping
    @PreAuthorize("hasRole('CLIENT')")
    public ResponseEntity<PageableDTO> getAllParkingByClient(@AuthenticationPrincipal JwtUserDetails user,
                                                             @PageableDefault(size = 5, sort = "entryDate",
                                                                     direction = Sort.Direction.ASC) Pageable pageable) {
        Page<ClientSpotProjection> projection = clientSpotService.findAllByUserId(user.getId(), pageable);
        PageableDTO dto = PageableMapper.toDto(projection);
        return ResponseEntity.ok(dto);
    }
}
